name: automated email sending

on:
    # schedule:
    #     - cron: 0 13 * * *
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo content
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10.7"

            - name: install python packages
              run: |
                  python3 -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Create token file
              run: |
                  echo "${{ secrets.TOKEN }}" > token.json

            - name: execute sportsnews.py
              env:
                  MONGODBURI: ${{ secrets.MONGODBURI }}
              run: python3 sportsnews.py
